# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30cf404a765596f4b9c9676cdb12d313eb19ca9435dd69aec81769686d6d9b1222341801446ed8ecc6b6827caa1b1e8f2487ebb917d2389227321f7a091fffa

test:
  secret_key_base: bf32ef04b6325c455df816b7dc04705e1d02f4b958e3ba3b655ccee7a66fa247db58957233e63361c7258edcb494cc3ca72df48a1639345fcb1af7e62230ac43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
